#!/usr/bin/env python3
"""Stamp a build id into index.html and emit a matching version.js.

Run after every change to index.html. The id is a content hash of the file
itself with the stamp blanked, so it changes exactly when the app changes and
not when you merely rebuild. That makes "is the deployed version the one I
think it is" a question with an answer.

    python3 build.py [dir]        default: ghpages/
"""
import hashlib, json, re, sys, time
from pathlib import Path

root = Path(sys.argv[1] if len(sys.argv) > 1 else "ghpages")
index = root / "index.html"
if not index.exists():
    sys.exit("no index.html in %s" % root)

src = index.read_text(encoding="utf-8")

STAMP = re.compile(r'const BUILD = "[^"]*";')
PLACEHOLDER = 'const BUILD = "";'

if STAMP.search(src):
    neutral = STAMP.sub(PLACEHOLDER, src)
else:
    # first run: insert the constant just after the opening of the main script
    anchor = '"use strict";'
    if anchor not in src:
        sys.exit("could not find the script entry point to stamp")
    src = src.replace(anchor, anchor + '\n' + PLACEHOLDER, 1)
    neutral = src

digest = hashlib.sha256(neutral.encode("utf-8")).hexdigest()[:12]
built = time.strftime("%Y-%m-%d %H:%M", time.localtime())
build_id = time.strftime("%Y%m%d-%H%M") + "-" + digest[:6]

stamped = STAMP.sub('const BUILD = "%s";' % build_id, neutral) \
    if STAMP.search(neutral) else neutral.replace(PLACEHOLDER, 'const BUILD = "%s";' % build_id, 1)
index.write_text(stamped, encoding="utf-8")

payload = {"build": build_id, "hash": digest, "built": built,
           "bytes": len(stamped)}
(root / "version.js").write_text(
    "// Generated by build.py — do not edit.\n"
    "window.ITL_BUILD = %s;\n" % json.dumps(payload, indent=2),
    encoding="utf-8")
(root / "version.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

print("build   %s" % build_id)
print("hash    %s" % digest)
print("built   %s" % built)
print("wrote   %s, version.js, version.json" % index.name)
